-- =====================================================================
-- ARCHIVO GENERADO — NO EDITAR A MANO
-- Fuente: config/permissions.json
-- Regenerar: node db/seeds/generate.mjs
-- =====================================================================

INSERT INTO platform.permissions
  (code, module, name, description, is_sensitive, requires_modules)
VALUES
  ('sales.create', 'sales', 'Registrar ventas', NULL, false, '{}'::text[]),
  ('sales.read', 'sales', 'Ver ventas', NULL, false, '{}'::text[]),
  ('sales.read_own', 'sales', 'Ver solo sus propias ventas', NULL, false, '{}'::text[]),
  ('sales.void', 'sales', 'Anular ventas', NULL, true, '{}'::text[]),
  ('sales.refund', 'sales', 'Registrar devoluciones', NULL, true, '{}'::text[]),
  ('sales.discount', 'sales', 'Aplicar descuentos', NULL, false, '{}'::text[]),
  ('sales.discount_override', 'sales', 'Superar el tope de descuento', NULL, true, '{}'::text[]),
  ('sales.price_override', 'sales', 'Modificar el precio en la venta', NULL, true, '{}'::text[]),
  ('sales.reprint', 'sales', 'Reimprimir tickets', NULL, false, '{}'::text[]),
  ('sales.hold', 'sales', 'Dejar ventas en espera', NULL, false, '{}'::text[]),
  ('sales.backdate', 'sales', 'Registrar ventas con fecha anterior', NULL, true, '{}'::text[]),
  ('products.read', 'products', 'Ver productos', NULL, false, '{}'::text[]),
  ('products.create', 'products', 'Crear productos', NULL, false, '{}'::text[]),
  ('products.update', 'products', 'Editar productos', NULL, false, '{}'::text[]),
  ('products.delete', 'products', 'Archivar productos', NULL, true, '{}'::text[]),
  ('products.price', 'products', 'Editar precios', NULL, true, '{}'::text[]),
  ('products.cost', 'products', 'Ver costos y márgenes', NULL, true, '{}'::text[]),
  ('products.attributes', 'products', 'Administrar campos dinámicos', NULL, false, '{}'::text[]),
  ('products.import', 'products', 'Importar catálogo masivo', NULL, false, '{}'::text[]),
  ('inventory.read', 'inventory', 'Ver existencias', NULL, false, '{}'::text[]),
  ('inventory.adjust', 'inventory', 'Ajustar existencias', NULL, true, '{}'::text[]),
  ('inventory.transfer', 'inventory', 'Transferir entre almacenes', NULL, false, '{}'::text[]),
  ('inventory.receive', 'inventory', 'Recibir mercancía', NULL, false, '{}'::text[]),
  ('inventory.count', 'inventory', 'Realizar conteos físicos', NULL, false, '{}'::text[]),
  ('inventory.count_approve', 'inventory', 'Aprobar conteos y aplicar diferencias', NULL, true, '{}'::text[]),
  ('inventory.consume', 'inventory', 'Registrar consumo de insumos', NULL, false, '{}'::text[]),
  ('inventory.scrap', 'inventory', 'Registrar mermas y descartes', NULL, true, '{}'::text[]),
  ('inventory.lots', 'inventory', 'Administrar lotes y vencimientos', NULL, false, '{}'::text[]),
  ('purchasing.read', 'purchasing', 'Ver compras y proveedores', NULL, false, '{}'::text[]),
  ('purchasing.create', 'purchasing', 'Crear órdenes de compra', NULL, false, '{}'::text[]),
  ('purchasing.approve', 'purchasing', 'Aprobar órdenes de compra', NULL, true, '{}'::text[]),
  ('purchasing.receive', 'purchasing', 'Registrar recepciones', NULL, false, '{}'::text[]),
  ('purchasing.suppliers', 'purchasing', 'Administrar proveedores', NULL, false, '{}'::text[]),
  ('purchasing.bills', 'purchasing', 'Administrar cuentas por pagar', NULL, false, '{}'::text[]),
  ('purchasing.pay', 'purchasing', 'Registrar pagos a proveedores', NULL, true, '{}'::text[]),
  ('credit.read', 'credit', 'Ver cuentas por cobrar', NULL, false, '{}'::text[]),
  ('credit.charge', 'credit', 'Vender a crédito / fiar', NULL, false, '{}'::text[]),
  ('credit.collect', 'credit', 'Registrar abonos', NULL, false, '{}'::text[]),
  ('credit.limit', 'credit', 'Definir límites de crédito', NULL, true, '{}'::text[]),
  ('credit.limit_override', 'credit', 'Fiar por encima del límite', NULL, true, '{}'::text[]),
  ('credit.waive', 'credit', 'Condonar intereses o mora', NULL, true, '{}'::text[]),
  ('credit.write_off', 'credit', 'Declarar incobrable', NULL, true, '{}'::text[]),
  ('credit.schedule', 'credit', 'Crear y editar cronogramas de pago', NULL, false, '{}'::text[]),
  ('credit.collection', 'credit', 'Ejecutar campañas de cobranza', NULL, false, '{}'::text[]),
  ('customers.read', 'customers', 'Ver clientes', NULL, false, '{}'::text[]),
  ('customers.create', 'customers', 'Crear clientes', NULL, false, '{}'::text[]),
  ('customers.update', 'customers', 'Editar clientes', NULL, false, '{}'::text[]),
  ('customers.delete', 'customers', 'Archivar clientes', NULL, true, '{}'::text[]),
  ('customers.export', 'customers', 'Exportar base de clientes', NULL, true, '{}'::text[]),
  ('cash.open', 'cash', 'Abrir caja', NULL, false, '{}'::text[]),
  ('cash.close', 'cash', 'Cerrar caja y arquear', NULL, false, '{}'::text[]),
  ('cash.read', 'cash', 'Ver sesiones de caja', NULL, false, '{}'::text[]),
  ('cash.withdraw', 'cash', 'Retirar efectivo', NULL, true, '{}'::text[]),
  ('cash.deposit', 'cash', 'Ingresar efectivo', NULL, false, '{}'::text[]),
  ('cash.approve_variance', 'cash', 'Aprobar cierres con descuadre', NULL, true, '{}'::text[]),
  ('cash.reopen', 'cash', 'Reabrir una caja cerrada', NULL, true, '{}'::text[]),
  ('finance.read', 'finance', 'Ver estado financiero y P&L', NULL, false, '{}'::text[]),
  ('finance.accounts', 'finance', 'Administrar cuentas bancarias', NULL, false, '{}'::text[]),
  ('finance.reconcile', 'finance', 'Conciliar movimientos', NULL, false, '{}'::text[]),
  ('expenses.read', 'expenses', 'Ver gastos', NULL, false, '{}'::text[]),
  ('expenses.create', 'expenses', 'Registrar gastos', NULL, false, '{}'::text[]),
  ('expenses.approve', 'expenses', 'Aprobar gastos', NULL, true, '{}'::text[]),
  ('expenses.categories', 'expenses', 'Administrar categorías de gasto', NULL, false, '{}'::text[]),
  ('taxes.read', 'taxes', 'Ver configuración fiscal', NULL, false, '{}'::text[]),
  ('taxes.configure', 'taxes', 'Configurar impuestos', NULL, true, '{}'::text[]),
  ('taxes.sequences', 'taxes', 'Administrar talonarios y folios', NULL, true, '{}'::text[]),
  ('taxes.issue', 'taxes', 'Emitir comprobantes fiscales', NULL, false, '{}'::text[]),
  ('taxes.cancel', 'taxes', 'Anular comprobantes fiscales', NULL, true, '{}'::text[]),
  ('taxes.einvoice', 'taxes', 'Transmitir facturación electrónica', NULL, false, '{}'::text[]),
  ('reports.sales', 'reports', 'Reportes de ventas', NULL, false, '{}'::text[]),
  ('reports.inventory', 'reports', 'Reportes de inventario', NULL, false, '{}'::text[]),
  ('reports.credit', 'reports', 'Reportes de cartera', NULL, false, '{}'::text[]),
  ('reports.finance', 'reports', 'Reportes financieros', NULL, false, '{}'::text[]),
  ('reports.employees', 'reports', 'Reportes de personal', NULL, false, '{}'::text[]),
  ('reports.agro', 'reports', 'Reportes agropecuarios', NULL, false, ARRAY['agro']::text[]),
  ('reports.export', 'reports', 'Exportar reportes', NULL, false, '{}'::text[]),
  ('agro.lots.read', 'agro', 'Ver lotes biológicos', NULL, false, ARRAY['agro']::text[]),
  ('agro.lots.create', 'agro', 'Crear lotes biológicos', NULL, false, ARRAY['agro']::text[]),
  ('agro.lots.update', 'agro', 'Editar lotes biológicos', NULL, false, ARRAY['agro']::text[]),
  ('agro.lot.close', 'agro', 'Cerrar un lote', NULL, true, ARRAY['agro']::text[]),
  ('agro.daily_record.create', 'agro', 'Registrar la jornada diaria', NULL, false, ARRAY['agro']::text[]),
  ('agro.daily_record.edit', 'agro', 'Corregir un registro diario', NULL, true, ARRAY['agro']::text[]),
  ('agro.schedule.read', 'agro', 'Ver el plan sanitario', NULL, false, ARRAY['agro']::text[]),
  ('agro.schedule.complete', 'agro', 'Marcar tareas sanitarias', NULL, false, ARRAY['agro']::text[]),
  ('agro.harvest.create', 'agro', 'Registrar faena o cosecha', NULL, false, ARRAY['agro']::text[]),
  ('agro.harvest.post', 'agro', 'Contabilizar faena y generar producto', NULL, true, ARRAY['agro']::text[]),
  ('agro.costing.read', 'agro', 'Ver costeo del lote', NULL, false, ARRAY['agro']::text[]),
  ('agro.farm_units', 'agro', 'Administrar galpones y unidades', NULL, false, ARRAY['agro']::text[]),
  ('appointments.read', 'appointments', 'Ver toda la agenda', NULL, false, ARRAY['appointments']::text[]),
  ('appointments.read_own', 'appointments', 'Ver su propia agenda', NULL, false, ARRAY['appointments']::text[]),
  ('appointments.create', 'appointments', 'Agendar citas', NULL, false, ARRAY['appointments']::text[]),
  ('appointments.update', 'appointments', 'Modificar cualquier cita', NULL, false, ARRAY['appointments']::text[]),
  ('appointments.update_own', 'appointments', 'Modificar sus propias citas', NULL, false, ARRAY['appointments']::text[]),
  ('appointments.cancel', 'appointments', 'Cancelar citas', NULL, false, ARRAY['appointments']::text[]),
  ('tables.read', 'tables', 'Ver el salón', NULL, false, ARRAY['tables']::text[]),
  ('tables.open', 'tables', 'Abrir mesas', NULL, false, ARRAY['tables']::text[]),
  ('tables.order', 'tables', 'Tomar comandas', NULL, false, ARRAY['tables']::text[]),
  ('tables.void_item', 'tables', 'Cancelar ítems enviados a cocina', NULL, true, ARRAY['tables']::text[]),
  ('tables.transfer', 'tables', 'Transferir cuentas entre mesas', NULL, false, ARRAY['tables']::text[]),
  ('tables.split', 'tables', 'Dividir cuentas', NULL, false, ARRAY['tables']::text[]),
  ('service_orders.read', 'service_orders', 'Ver órdenes de servicio', NULL, false, ARRAY['service_orders']::text[]),
  ('service_orders.create', 'service_orders', 'Crear órdenes de servicio', NULL, false, ARRAY['service_orders']::text[]),
  ('service_orders.update', 'service_orders', 'Actualizar diagnóstico y avance', NULL, false, ARRAY['service_orders']::text[]),
  ('service_orders.quote', 'service_orders', 'Cotizar reparaciones', NULL, false, ARRAY['service_orders']::text[]),
  ('service_orders.deliver', 'service_orders', 'Entregar y cerrar órdenes', NULL, false, ARRAY['service_orders']::text[]),
  ('employees.read', 'employees', 'Ver empleados', NULL, false, '{}'::text[]),
  ('employees.manage', 'employees', 'Administrar empleados', NULL, true, '{}'::text[]),
  ('attendance.clock', 'employees', 'Marcar entrada y salida', NULL, false, '{}'::text[]),
  ('attendance.read', 'employees', 'Ver marcajes de asistencia', NULL, false, '{}'::text[]),
  ('attendance.edit', 'employees', 'Corregir marcajes', NULL, true, '{}'::text[]),
  ('commissions.read', 'employees', 'Ver todas las comisiones', NULL, false, '{}'::text[]),
  ('commissions.read_own', 'employees', 'Ver sus propias comisiones', NULL, false, '{}'::text[]),
  ('commissions.settle', 'employees', 'Liquidar comisiones', NULL, true, '{}'::text[]),
  ('payroll.read', 'employees', 'Ver información de nómina', NULL, true, '{}'::text[]),
  ('loyalty.read', 'loyalty', 'Ver programas y saldos', NULL, false, ARRAY['loyalty']::text[]),
  ('loyalty.configure', 'loyalty', 'Configurar programas', NULL, false, ARRAY['loyalty']::text[]),
  ('loyalty.redeem', 'loyalty', 'Canjear puntos o cashback', NULL, false, ARRAY['loyalty']::text[]),
  ('loyalty.adjust', 'loyalty', 'Ajustar saldos manualmente', NULL, true, ARRAY['loyalty']::text[]),
  ('loyalty.campaigns', 'loyalty', 'Enviar campañas', NULL, false, ARRAY['loyalty']::text[]),
  ('storefront.read', 'storefront', 'Ver la tienda y sus pedidos', NULL, false, ARRAY['storefront']::text[]),
  ('storefront.configure', 'storefront', 'Configurar la tienda', NULL, false, ARRAY['storefront']::text[]),
  ('storefront.publish', 'storefront', 'Publicar o despublicar la tienda', NULL, false, ARRAY['storefront']::text[]),
  ('storefront.orders', 'storefront', 'Gestionar pedidos online', NULL, false, ARRAY['storefront']::text[]),
  ('messaging.send', 'messaging', 'Enviar mensajes a clientes', NULL, false, '{}'::text[]),
  ('messaging.templates', 'messaging', 'Administrar plantillas', NULL, false, '{}'::text[]),
  ('messaging.accounts', 'messaging', 'Conectar cuentas de WhatsApp', NULL, true, '{}'::text[]),
  ('messaging.bulk', 'messaging', 'Enviar campañas masivas', NULL, true, '{}'::text[]),
  ('settings.read', 'settings', 'Ver configuración del negocio', NULL, false, '{}'::text[]),
  ('settings.update', 'settings', 'Editar configuración del negocio', NULL, true, '{}'::text[]),
  ('settings.profile', 'settings', 'Cambiar el perfil de negocio', NULL, true, '{}'::text[]),
  ('settings.branches', 'settings', 'Administrar sucursales y almacenes', NULL, false, '{}'::text[]),
  ('settings.devices', 'settings', 'Administrar dispositivos', NULL, false, '{}'::text[]),
  ('settings.billing', 'settings', 'Administrar la suscripción', NULL, true, '{}'::text[]),
  ('users.read', 'users', 'Ver usuarios', NULL, false, '{}'::text[]),
  ('users.invite', 'users', 'Invitar usuarios', NULL, true, '{}'::text[]),
  ('users.manage', 'users', 'Administrar usuarios', NULL, true, '{}'::text[]),
  ('users.roles', 'users', 'Administrar roles y permisos', NULL, true, '{}'::text[]),
  ('audit.read', 'audit', 'Ver la bitácora de auditoría', NULL, true, '{}'::text[]),
  ('audit.verify', 'audit', 'Verificar la cadena de integridad', NULL, true, '{}'::text[]),
  ('sync.conflicts', 'audit', 'Ver y resolver conflictos de sincronización', NULL, false, '{}'::text[])
ON CONFLICT (code) DO UPDATE
  SET module = EXCLUDED.module,
      name = EXCLUDED.name,
      description = EXCLUDED.description,
      is_sensitive = EXCLUDED.is_sensitive,
      requires_modules = EXCLUDED.requires_modules;
